### ISSUE TITLE
Cannot reflash licensed JESC after downgrading back to BlHeli_S firmware (iNav 3.0)

### ISSUE THREAD

**Issue by AlexC176** [jflight-public/jesc-configurator#105]
Sequence of events
  
Flight controller info, identifier: INAV, version: 3.0.0

 1) flashed JESC ok - not the version (no damping) I actually needed for my flying wing
 2) licensed the ESC ok, config gave the message "licensed but not activated", did not enable telemetry
 3) tried to re-flash the version I need -
   ESC 1: flashing failed - Error: Version mismatch at checkESCAndMCU (chrome-extension://maigancljkhnkhpejlfmgjjmjafafdhp/js/build/blheli_configurator.js:1076:47) at _fulfilled (chrome-extension://maigancljkhnkhpejlfmgjjmjafafdhp/js/libraries/q.js:794:58) at chrome-extension://maigancljkhnkhpejlfmgjjmjafafdhp/js/libraries/q.js:823:34 at Promise.promise.promiseDispatch (chrome-extension://maigancljkhnkhpejlfmgjjmjafafdhp/js/libraries/q.js:756:17) at chrome-extension://maigancljkhnkhpejlfmgjjmjafafdhp/js/libraries/q.js:564:48 at flush (chrome-extension://maigancljkhnkhpejlfmgjjmjafafdhp/js/libraries/q.js:110:21) at processTicksAndRejections (internal/process/task_queues.js:75:11)

 4) Downgraded esc back to BLHeli suite, flash back to BLHeli - flash back went ok
 5) Back to JESC to flash what I need, same error
 ESC 1: flashing failed - Error: Version mismatch at checkESCAndMCU (chrome-extension://maigancljkhnkhpejlfmgjjmjafafdhp/js/build/blheli_configurator.js:1076:47) at _fulfilled (chrome-extension://maigancljkhnkhpejlfmgjjmjafafdhp/js/libraries/q.js:794:58) at chrome-extension://maigancljkhnkhpejlfmgjjmjafafdhp/js/libraries/q.js:823:34 at Promise.promise.promiseDispatch (chrome-extension://maigancljkhnkhpejlfmgjjmjafafdhp/js/libraries/q.js:756:17) at chrome-extension://maigancljkhnkhpejlfmgjjmjafafdhp/js/libraries/q.js:564:48 at flush (chrome-extension://maigancljkhnkhpejlfmgjjmjafafdhp/js/libraries/q.js:110:21) at 

Ignore inappropriate MCU and Layout? Checkbox tried but same error at the start of flash.

Please help ! thanks Alex

**Comment by AlexC176** [comment]
[Log.txt](https://github.com/jflight-public/jesc-configurator/files/7448018/Log.txt)

**Comment by AlexC176** [comment]
The problem is related to licensing and the code. Once a JESC is licensed there is a specific line in the code that checks for error if protocol <108 (Betaflight 4.1). INav is always protocol 107, therefore licensed JESC are un-flashable under iNav.
