### ISSUE TITLE
Failed to flash 4in1 esc

### ISSUE THREAD

**Issue by donchia** [jflight-public/jesc-configurator#45]
Followed the guides and flash of esc fails.
ESC 4: flashing <strong>started</strong>
sending cmd_DeviceInitFlash 0 3
received cmd_DeviceInitFlash ACK_OK 0 178,232,100,1
sending cmd_DeviceRead 1a00 112
received cmd_DeviceRead ACK_OK 1a00 16,79,33,255,255,255,255,255,255,9,255,2,255,85,170,1,255,255,255,255,255,3,255,255,255,0,250,40,80,4,255,2,255,122,255,7,1,255,255,0,0,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,35,74,95,72,95,49,53,35,32,32,32,32,32,32,32,32,35,66,76,72,69,76,73,36,69,70,77,56,66,50,49,35,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32
Please install BetaFlight >= 4.1 before flashing Telemetry!
ESC 4: flashing <span style="color: red">failed</span> - <strong>Error: Version mismatch
    at checkESCAndMCU (chrome-extension://maigancljkhnkhpejlfmgjjmjafafdhp/js/build/blheli_configurator.js:1078:47)
    at _fulfilled (chrome-extension://maigancljkhnkhpejlfmgjjmjafafdhp/js/libraries/q.js:794:58)
    at chrome-extension://maigancljkhnkhpejlfmgjjmjafafdhp/js/libraries/q.js:823:34
    at Promise.promise.promiseDispatch (chrome-extension://maigancljkhnkhpejlfmgjjmjafafdhp/js/libraries/q.js:756:17)
    at chrome-extension://maigancljkhnkhpejlfmgjjmjafafdhp/js/libraries/q.js:564:48
    at flush (chrome-extension://maigancljkhnkhpejlfmgjjmjafafdhp/js/libraries/q.js:110:21)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)</strong>

**Comment by joelucid** [comment]
The log says it all: "Please install BetaFlight >= 4.1 before flashing Telemetry!"
