### ISSUE TITLE
Can't flash my ESC

### ISSUE THREAD

**Issue by Ciolouse** [jflight-public/jesc-configurator#77]
Greetings,

I'm trying to flash my ESC, but impossible, every time I get this error for all the 4 ESC:

2020-10-06 @ 14:35:27 -- ESC 1: flashing failed - Error: Version mismatch at checkESCAndMCU (chrome-extension://maigancljkhnkhpejlfmgjjmjafafdhp/js/build/blheli_configurator.js:1076:47) at _fulfilled (chrome-extension://maigancljkhnkhpejlfmgjjmjafafdhp/js/libraries/q.js:794:58) at chrome-extension://maigancljkhnkhpejlfmgjjmjafafdhp/js/libraries/q.js:823:34 at Promise.promise.promiseDispatch (chrome-extension://maigancljkhnkhpejlfmgjjmjafafdhp/js/libraries/q.js:756:17) at chrome-extension://maigancljkhnkhpejlfmgjjmjafafdhp/js/libraries/q.js:564:48 at flush (chrome-extension://maigancljkhnkhpejlfmgjjmjafafdhp/js/libraries/q.js:110:21) at processTicksAndRejections (internal/process/task_queues.js:75:11)

I tried with JESC Configurator 1.2.9 and 1.2.8.

Can you help me please ?

**Comment by Ciolouse** [comment]
I'm trying to flash my Mobula6, with Betaflight 3.5.7.

![BLHeliSuiteSiLabs ESC Setup_201006_1](https://user-images.githubusercontent.com/22751878/95316923-c0565f00-0894-11eb-940d-e8daa0723293.png)

![BLHeliSuiteESC overview_201006_1](https://user-images.githubusercontent.com/22751878/95316935-c3514f80-0894-11eb-8a07-dc90c52f404d.png)

**Comment by Ciolouse** [comment]
Here is the error log.
[Log.txt](https://github.com/jflight-public/jesc-configurator/files/5342890/Log.txt)

**Comment by Ciolouse** [comment]
Updated Betaflight to version 4.2.3 and now it is working.
But I see on lot of videos that this was working on Betaflight 3.5.7.
