### ISSUE TITLE
Impossible to write or flash ESC

### ISSUE THREAD

**Issue by flixiflux** [jflight-public/jesc-configurator#90]
Hello,

Sorry but after searching for weeks and trying lots of things I’m really lost and would really like to be able to flash my ESCs. I want to put it in 48hz but the most important, be able to use turtle mode (motors don’t reverse when turtle mode).

I bought a US65 (crazybeeF3FR) to somebody but it’s totally impossible to flash ESC, in the configurator you can’t save anything, even if I just want to write a simple setting:/ I doesn’t work in jesc configurator, jazzmaverick, blheli configurator, blheli suite.

Here is the log error when trying to flash. If someone could give me advises it would be great as I really worked on it for hours now:(

Thanks for reading me :)

```
`ESC 4: flashing <strong>started</strong>
sending cmd_DeviceInitFlash 0 3
received cmd_DeviceInitFlash ACK_OK 0 177,232,100,1
sending cmd_DeviceRead 1a00 112
received cmd_DeviceRead ACK_OK 1a00 16,5,33,255,255,255,255,255,255,11,255,1,255,85,170,1,255,255,255,255,255,3,255,255,255,37,208,40,80,4,255,2,255,122,255,7,1,255,255,0,0,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,35,79,95,76,95,48,53,35,32,32,32,32,32,32,32,32,35,66,76,72,69,76,73,36,69,70,77,56,66,49,48,35,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32
sending cmd_DevicePageErase 0 13
received cmd_DevicePageErase ACK_D_GENERAL_ERROR 1a00 13
163552.1800001152 resending cmd_DevicePageErase 0 13
163558.29500011168 resending cmd_InterfaceTestAlive 0 0
163558.60499991104 resending cmd_InterfaceTestAlive 0 0
163558.77000000328 resending cmd_InterfaceTestAlive 0 0
received cmd_DevicePageErase ACK_D_GENERAL_ERROR 1a00 13
163569.3550000433 resending cmd_DevicePageErase 0 13
received cmd_DevicePageErase ACK_D_GENERAL_ERROR 1a00 13
163583.0099999439 resending cmd_DevicePageErase 0 13
received cmd_DevicePageErase ACK_D_GENERAL_ERROR 1a00 13
163605.34500004724 resending cmd_DevicePageErase 0 13
received cmd_DevicePageErase ACK_D_GENERAL_ERROR 1a00 13
ESC 4: flashing <span style="color: red">failed</span> - <strong>Error: cmd_DevicePageErase ACK_D_GENERAL_ERROR
    at recvCallback (chrome-extension://maigancljkhnkhpejlfmgjjmjafafdhp/js/_4way_if.js:210:37)
    at chrome-extension://maigancljkhnkhpejlfmgjjmjafafdhp/js/_4way_if.js:316:29
    at Array.forEach (<anonymous>)
    at Object.onread (chrome-extension://maigancljkhnkhpejlfmgjjmjafafdhp/js/_4way_if.js:298:18)
    at read_serial (chrome-extension://maigancljkhnkhpejlfmgjjmjafafdhp/js/serial_backend.js:234:15)</strong>

`
```

**Comment by flixiflux** [comment]
Sorry, I didn't mention it's on the last betaflight firmware available (4.0.6)
